alternate: Jalen's Blog

# Assets
statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
# Usage: `Key: /link/ || icon`
# Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
# Value before `||` delimeter is the target link.
# Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart
  # links: /links/ || magic
  webstack: /webstack/ || user
  # travellings: /travellings/ || books
  # about: 
  # commonweal

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/SincerelyUnique || github || "#191717"
  #google: https://plus.google.com/yourname || google
  twitter: https://twitter.com/jalen_chu || twitter || "#00aff0"
  zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  # csdn: https://blog.csdn.net/baidu_30809315 || csdn || "#ea716e"
  music: https://music.163.com/#/my/m/music/playlist?id=2031973464 || cloud-music || "#e60026"
  #weibo: https://weibo.com/amehime || weibo || "#ea716e"
  # oschina: https://my.oschina.net/chumingcheng || oschina || "#ea716e"
  about: https://about.me/JalenChu || address-card || "#3b5998"
  # email: mailto:1152357479@qq.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2015
  count: true

post:
  count: true


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  appId: 7zazslgUIl5UsRfVMdPouomw-gzGzoHsz #这里不要忘了改
  appKey: jX6FxzLEiu8sQD0tX7c5wrj4 #这里不要忘了改
  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
  pageSize: 10 # Pagination size
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  lang: zh-CN
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true
  tagMeta:
    visitor: 新朋友
    master: 主人
    friend: 小伙伴
    investor: 金主粑粑
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
    # - hash of master@email.com
    # - hash of master2@email.com
    friend:
      - deea5a8d259d17182a53be1772e4c182
    investor:
    # - hash of investor1@email.com

# bgm
audio:
  - title: 列表1
    list:
      - https://music.163.com/#/playlist?id=6773033546
      - https://music.163.com/#/playlist?id=6773033546
  - title: 列表2
    list:
      - https://music.163.com/#/playlist?id=6773033546

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------


# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true
